# Selecting Subsets of Data

In [1]:
import pandas as pd

pd.set_option("display.max_columns", 4, "display.max_rows", 10, "display.max_colwidth", 12)

## Introduction

## Selecting Series data

### How to do it...

In [2]:
college = pd.read_csv("../data/college.csv", index_col="INSTNM")
city = college["CITY"]
city

INSTNM
Alabama A & M University                                       Normal
University of Alabama at Birmingham                        Birmingham
Amridge University                                         Montgomery
University of Alabama in Huntsville                        Huntsville
Alabama State University                                   Montgomery
                                                             ...
SAE Institute of Technology  San Francisco                 Emeryville
Rasmussen College - Overland Park                         Overland...
National Personal Training Institute of Cleveland         Highland...
Bay Area Medical Academy - San Jose Satellite Location       San Jose
Excel Learning Center-San Antonio South                   San Antonio
Name: CITY, Length: 7535, dtype: object

In [3]:
city["Alabama A & M University"]

'Normal'

In [4]:
city.loc["Alabama A & M University"]

'Normal'

In [5]:
city[["Alabama A & M University", "Alabama State University"]]

INSTNM
Alabama A & M University        Normal
Alabama State University    Montgomery
Name: CITY, dtype: object

In [6]:
city.loc[["Alabama A & M University", "Alabama State University"]]

INSTNM
Alabama A & M University        Normal
Alabama State University    Montgomery
Name: CITY, dtype: object

In [7]:
city.iloc[[0, 4]]

INSTNM
Alabama A & M University        Normal
Alabama State University    Montgomery
Name: CITY, dtype: object

In [8]:
city["Alabama A & M University":"Alabama State University"]

INSTNM
Alabama A & M University                   Normal
University of Alabama at Birmingham    Birmingham
Amridge University                     Montgomery
University of Alabama in Huntsville    Huntsville
Alabama State University               Montgomery
Name: CITY, dtype: object

In [9]:
city[0:5]

INSTNM
Alabama A & M University                   Normal
University of Alabama at Birmingham    Birmingham
Amridge University                     Montgomery
University of Alabama in Huntsville    Huntsville
Alabama State University               Montgomery
Name: CITY, dtype: object

In [10]:
city.loc["Alabama A & M University":"Alabama State University"]

INSTNM
Alabama A & M University                   Normal
University of Alabama at Birmingham    Birmingham
Amridge University                     Montgomery
University of Alabama in Huntsville    Huntsville
Alabama State University               Montgomery
Name: CITY, dtype: object

In [11]:
city.iloc[0:5]

INSTNM
Alabama A & M University                   Normal
University of Alabama at Birmingham    Birmingham
Amridge University                     Montgomery
University of Alabama in Huntsville    Huntsville
Alabama State University               Montgomery
Name: CITY, dtype: object

In [12]:
alabama_mask = city.isin(["Birmingham", "Montgomery"])
city[alabama_mask]

INSTNM
University of Alabama at Birmingham    Birmingham
Amridge University                     Montgomery
Alabama State University               Montgomery
Auburn University at Montgomery        Montgomery
Birmingham Southern College            Birmingham
                                          ...
Fortis Institute-Birmingham            Birmingham
Hair Academy                           Montgomery
Brown Mackie College-Birmingham        Birmingham
Nunation School of Cosmetology         Birmingham
Troy University-Montgomery Campus      Montgomery
Name: CITY, Length: 26, dtype: object

### How it works...

In [13]:
s = pd.Series([10, 20, 35, 28], index=[5, 2, 3, 1])
s

5    10
2    20
3    35
1    28
dtype: int64

In [14]:
s[0:4]

5    10
2    20
3    35
1    28
dtype: int64

In [15]:
s[5]

10

In [16]:
s[1]

28

### There's more...

In [17]:
college.loc["Alabama A & M University", "CITY"]

'Normal'

In [18]:
college.iloc[0, 0]

'Normal'

In [19]:
college.loc[["Alabama A & M University", "Alabama State University"], "CITY"]

INSTNM
Alabama A & M University        Normal
Alabama State University    Montgomery
Name: CITY, dtype: object

In [20]:
college.iloc[[0, 4], 0]

INSTNM
Alabama A & M University        Normal
Alabama State University    Montgomery
Name: CITY, dtype: object

In [21]:
college.loc["Alabama A & M University":"Alabama State University", "CITY"]

INSTNM
Alabama A & M University                   Normal
University of Alabama at Birmingham    Birmingham
Amridge University                     Montgomery
University of Alabama in Huntsville    Huntsville
Alabama State University               Montgomery
Name: CITY, dtype: object

In [22]:
college.iloc[0:5, 0]

INSTNM
Alabama A & M University                   Normal
University of Alabama at Birmingham    Birmingham
Amridge University                     Montgomery
University of Alabama in Huntsville    Huntsville
Alabama State University               Montgomery
Name: CITY, dtype: object

In [23]:
city.loc["Reid State Technical College":"Alabama State University"]

Series([], Name: CITY, dtype: object)

## Selecting DataFrame rows

In [24]:
college = pd.read_csv("../data/college.csv", index_col="INSTNM")
college.sample(5, random_state=42)

                     CITY STABBR  ...  MD_EARN_WNE_P10  GRAD_DEBT_MDN_SUPP
INSTNM                            ...
Career Po...  San Antonio     TX  ...        20700            14977
Ner Israe...    Baltimore     MD  ...  PrivacyS...      PrivacyS...
Reflectio...      Decatur     IL  ...          NaN      PrivacyS...
Capital A...  Baton Rouge     LA  ...        26400      PrivacyS...
West Virg...   Montgomery     WV  ...        43400            23969

[5 rows x 26 columns]

In [25]:
college.iloc[60]

CITY                  Anchorage
STABBR                       AK
HBCU                        0.0
MENONLY                     0.0
WOMENONLY                   0.0
                        ...
PCTPELL                  0.2385
PCTFLOAN                 0.2647
UG25ABV                  0.4386
MD_EARN_WNE_P10           42500
GRAD_DEBT_MDN_SUPP      19449.5
Name: University of Alaska Anchorage, Length: 26, dtype: object

In [26]:
college.loc["University of Alaska Anchorage"]

CITY                  Anchorage
STABBR                       AK
HBCU                        0.0
MENONLY                     0.0
WOMENONLY                   0.0
                        ...
PCTPELL                  0.2385
PCTFLOAN                 0.2647
UG25ABV                  0.4386
MD_EARN_WNE_P10           42500
GRAD_DEBT_MDN_SUPP      19449.5
Name: University of Alaska Anchorage, Length: 26, dtype: object

In [27]:
college.iloc[[60, 99, 3]]

                    CITY STABBR  ...  MD_EARN_WNE_P10  GRAD_DEBT_MDN_SUPP
INSTNM                           ...
Universit...   Anchorage     AK  ...        42500          19449.5
Internati...       Tempe     AZ  ...        22200            10556
Universit...  Huntsville     AL  ...        45500            24097

[3 rows x 26 columns]

In [28]:
labels = [
    "University of Alaska Anchorage",
    "International Academy of Hair Design",
    "University of Alabama in Huntsville",
]
college.loc[labels]

                    CITY STABBR  ...  MD_EARN_WNE_P10  GRAD_DEBT_MDN_SUPP
INSTNM                           ...
Universit...   Anchorage     AK  ...        42500          19449.5
Internati...       Tempe     AZ  ...        22200            10556
Universit...  Huntsville     AL  ...        45500            24097

[3 rows x 26 columns]

In [29]:
college.iloc[99:102]

                 CITY STABBR  ...  MD_EARN_WNE_P10  GRAD_DEBT_MDN_SUPP
INSTNM                        ...
Internati...    Tempe     AZ  ...        22200            10556
GateWay C...  Phoenix     AZ  ...        29800             7283
Mesa Comm...     Mesa     AZ  ...        35200             8000

[3 rows x 26 columns]

In [30]:
start = "International Academy of Hair Design"
stop = "Mesa Community College"
college.loc[start:stop]

                 CITY STABBR  ...  MD_EARN_WNE_P10  GRAD_DEBT_MDN_SUPP
INSTNM                        ...
Internati...    Tempe     AZ  ...        22200            10556
GateWay C...  Phoenix     AZ  ...        29800             7283
Mesa Comm...     Mesa     AZ  ...        35200             8000

[3 rows x 26 columns]

### How it works...

### There's more...

In [31]:
college.iloc[[60, 99, 3]].index.tolist()

['University of Alaska Anchorage',
 'International Academy of Hair Design',
 'University of Alabama in Huntsville']

## Selecting DataFrame rows and columns simultaneously

### How to do it...

In [32]:
college = pd.read_csv("data/college.csv", index_col="INSTNM")
college.iloc[:3, :4]

FileNotFoundError: [Errno 2] No such file or directory: 'data/college.csv'

In [33]:
college.loc[:"Amridge University", :"MENONLY"]

                    CITY STABBR  HBCU  MENONLY
INSTNM
Alabama A...      Normal     AL   1.0      0.0
Universit...  Birmingham     AL   0.0      0.0
Amridge U...  Montgomery     AL   0.0      0.0

In [34]:
college.iloc[:, [4, 6]].head()

              WOMENONLY  SATVRMID
INSTNM
Alabama A...        0.0     424.0
Universit...        0.0     570.0
Amridge U...        0.0       NaN
Universit...        0.0     595.0
Alabama S...        0.0     425.0

In [35]:
college.loc[:, ["WOMENONLY", "SATVRMID"]].head()

              WOMENONLY  SATVRMID
INSTNM
Alabama A...        0.0     424.0
Universit...        0.0     570.0
Amridge U...        0.0       NaN
Universit...        0.0     595.0
Alabama S...        0.0     425.0

In [36]:
college.iloc[[100, 200], [7, 15]]

              SATMTMID  UGDS_NHPI
INSTNM
GateWay C...       NaN     0.0029
American ...       NaN        NaN

In [37]:
rows = ["GateWay Community College", "American Baptist Seminary of the West"]
columns = ["SATMTMID", "UGDS_NHPI"]
college.loc[rows, columns]

              SATMTMID  UGDS_NHPI
INSTNM
GateWay C...       NaN     0.0029
American ...       NaN        NaN

In [38]:
college.iloc[5, -4]

0.401

In [39]:
college.loc["The University of Alabama", "PCTFLOAN"]

0.401

In [40]:
college.iloc[90:80:-2, 5]

INSTNM
Empire Beauty School-Flagstaff     0
Charles of Italy Beauty College    0
Central Arizona College            0
University of Arizona              0
Arizona State University-Tempe     0
Name: RELAFFIL, dtype: int64

In [41]:
start = "Empire Beauty School-Flagstaff"
stop = "Arizona State University-Tempe"
college.loc[start:stop:-2, "RELAFFIL"]

INSTNM
Empire Beauty School-Flagstaff     0
Charles of Italy Beauty College    0
Central Arizona College            0
University of Arizona              0
Arizona State University-Tempe     0
Name: RELAFFIL, dtype: int64

### How it works...

### There's more...

## Selecting data with both integers and labels

### How to do it...

In [43]:
college = pd.read_csv("../data/college.csv", index_col="INSTNM")

In [44]:
col_start = college.columns.get_loc("UGDS_WHITE")
col_end = college.columns.get_loc("UGDS_UNKN") + 1
col_start, col_end

(10, 19)

In [45]:
college.iloc[:5, col_start:col_end]

              UGDS_WHITE  UGDS_BLACK  ...  UGDS_NRA  UGDS_UNKN
INSTNM                                ...
Alabama A...      0.0333      0.9353  ...    0.0059     0.0138
Universit...      0.5922      0.2600  ...    0.0179     0.0100
Amridge U...      0.2990      0.4192  ...    0.0000     0.2715
Universit...      0.6988      0.1255  ...    0.0332     0.0350
Alabama S...      0.0158      0.9208  ...    0.0243     0.0137

[5 rows x 9 columns]

### How it works...

### There's more...

In [46]:
row_start = college.index[10]
row_end = college.index[15]
college.loc[row_start:row_end, "UGDS_WHITE":"UGDS_UNKN"]

              UGDS_WHITE  UGDS_BLACK  ...  UGDS_NRA  UGDS_UNKN
INSTNM                                ...
Birmingha...      0.7983      0.1102  ...    0.0000     0.0051
Chattahoo...      0.4661      0.4372  ...    0.0000     0.0139
Concordia...      0.0280      0.8758  ...    0.0466     0.0000
South Uni...      0.3046      0.6054  ...    0.0019     0.0326
Enterpris...      0.6408      0.2435  ...    0.0012     0.0069
James H F...      0.6979      0.2259  ...    0.0007     0.0009

[6 rows x 9 columns]

In [47]:
college.ix[10:16, "UGDS_WHITE":"UGDS_UNKN"]

AttributeError: 'DataFrame' object has no attribute 'ix'

In [48]:
college.iloc[10:16].loc[:, "UGDS_WHITE":"UGDS_UNKN"]

              UGDS_WHITE  UGDS_BLACK  ...  UGDS_NRA  UGDS_UNKN
INSTNM                                ...
Birmingha...      0.7983      0.1102  ...    0.0000     0.0051
Chattahoo...      0.4661      0.4372  ...    0.0000     0.0139
Concordia...      0.0280      0.8758  ...    0.0466     0.0000
South Uni...      0.3046      0.6054  ...    0.0019     0.0326
Enterpris...      0.6408      0.2435  ...    0.0012     0.0069
James H F...      0.6979      0.2259  ...    0.0007     0.0009

[6 rows x 9 columns]

## Slicing lexicographically

### How to do it...

In [49]:
college = pd.read_csv("../data/college.csv", index_col="INSTNM")

In [50]:
college.loc["Sp":"Su"]

KeyError: 'Sp'

In [51]:
college = college.sort_index()

In [52]:
college.loc["Sp":"Su"]

                    CITY STABBR  ...  MD_EARN_WNE_P10  GRAD_DEBT_MDN_SUPP
INSTNM                           ...
Spa Tech ...     Ipswich     MA  ...        21500             6333
Spa Tech ...    Plymouth     MA  ...        21500             6333
Spa Tech ...    Westboro     MA  ...        21500             6333
Spa Tech ...   Westbrook     ME  ...        21500             6333
Spalding ...  Louisville     KY  ...        41700            25000
...                  ...    ...  ...          ...              ...
Studio Ac...    Chandler     AZ  ...          NaN             6333
Studio Je...    New York     NY  ...  PrivacyS...      PrivacyS...
Stylemast...    Longview     WA  ...        17000            13320
Styles an...      Selmer     TN  ...  PrivacyS...      PrivacyS...
Styletren...   Rock Hill     SC  ...  PrivacyS...           9495.5

[201 rows x 26 columns]

### How it works...

### There's more...

In [53]:
college = college.sort_index(ascending=False)
college.index.is_monotonic_decreasing

True

In [54]:
college.loc["E":"B"]

                     CITY STABBR  ...  MD_EARN_WNE_P10  GRAD_DEBT_MDN_SUPP
INSTNM                            ...
Dyersburg...    Dyersburg     TN  ...        26800             7475
Dutchess ...  Poughkee...     NY  ...        32500            10250
Dutchess ...  Poughkee...     NY  ...        36500             9500
Durham Te...       Durham     NC  ...        27200          11069.5
Durham Be...       Durham     NC  ...  PrivacyS...            15332
...                   ...    ...  ...          ...              ...
Bacone Co...     Muskogee     OK  ...        29700            26350
Babson Co...    Wellesley     MA  ...        86700            27000
BJ's Beau...       Auburn     WA  ...          NaN      PrivacyS...
BIR Train...      Chicago     IL  ...  PrivacyS...            15394
B M Spurr...    Glen Dale     WV  ...  PrivacyS...      PrivacyS...

[1411 rows x 26 columns]