# Restructuring Data into a Tidy Form

In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', 8, 'display.max_rows', 10, 'display.max_colwidth', 40)

## Introduction

## Tidying variable values as column names with stack

In [4]:
state_fruit = pd.read_csv('../data/state_fruit.csv', index_col=0)
state_fruit

         Apple  Orange  Banana
Texas       12      10      40
Arizona      9       7      12
Florida      0      14     190

### How to do it...

In [5]:
state_fruit.stack()

Texas    Apple      12
         Orange     10
         Banana     40
Arizona  Apple       9
         Orange      7
         Banana     12
Florida  Apple       0
         Orange     14
         Banana    190
dtype: int64

In [6]:
(state_fruit
   .stack()
   .reset_index()
)

   level_0 level_1    0
0    Texas   Apple   12
1    Texas  Orange   10
2    Texas  Banana   40
3  Arizona   Apple    9
4  Arizona  Orange    7
5  Arizona  Banana   12
6  Florida   Apple    0
7  Florida  Orange   14
8  Florida  Banana  190

In [7]:
(state_fruit
   .stack()
   .reset_index()
   .rename(columns={
        'level_0':'state',
        'level_1': 'fruit',
        0: 'weight'
        })
)

     state   fruit  weight
0    Texas   Apple      12
1    Texas  Orange      10
2    Texas  Banana      40
3  Arizona   Apple       9
4  Arizona  Orange       7
5  Arizona  Banana      12
6  Florida   Apple       0
7  Florida  Orange      14
8  Florida  Banana     190

In [8]:
(state_fruit
    .stack()
    .rename_axis(['state', 'fruit'])
)

state    fruit
Texas    Apple      12
         Orange     10
         Banana     40
Arizona  Apple       9
         Orange      7
         Banana     12
Florida  Apple       0
         Orange     14
         Banana    190
dtype: int64

In [9]:
(state_fruit
    .stack()
    .rename_axis(['state', 'fruit'])
    .reset_index(name='weight')
)

     state   fruit  weight
0    Texas   Apple      12
1    Texas  Orange      10
2    Texas  Banana      40
3  Arizona   Apple       9
4  Arizona  Orange       7
5  Arizona  Banana      12
6  Florida   Apple       0
7  Florida  Orange      14
8  Florida  Banana     190

### How it works...

### There's more...

In [10]:
state_fruit2 = pd.read_csv('../data/state_fruit2.csv')
state_fruit2

     State  Apple  Orange  Banana
0    Texas     12      10      40
1  Arizona      9       7      12
2  Florida      0      14     190

In [11]:
state_fruit2.stack()

0  State       Texas
   Apple          12
   Orange         10
   Banana         40
1  State     Arizona
              ...
   Banana         12
2  State     Florida
   Apple           0
   Orange         14
   Banana        190
Length: 12, dtype: object

In [12]:
state_fruit2.set_index('State').stack()

State
Texas    Apple      12
         Orange     10
         Banana     40
Arizona  Apple       9
         Orange      7
         Banana     12
Florida  Apple       0
         Orange     14
         Banana    190
dtype: int64

## Tidying variable values as column names with melt

### How to do it...

In [13]:
state_fruit2 = pd.read_csv('../data/state_fruit2.csv')
state_fruit2

     State  Apple  Orange  Banana
0    Texas     12      10      40
1  Arizona      9       7      12
2  Florida      0      14     190

In [14]:
state_fruit2.melt(id_vars=['State'],
    value_vars=['Apple', 'Orange', 'Banana'])

     State variable  value
0    Texas    Apple     12
1  Arizona    Apple      9
2  Florida    Apple      0
3    Texas   Orange     10
4  Arizona   Orange      7
5  Florida   Orange     14
6    Texas   Banana     40
7  Arizona   Banana     12
8  Florida   Banana    190

In [15]:
state_fruit2.melt(id_vars=['State'],
                   value_vars=['Apple', 'Orange', 'Banana'],
                   var_name='Fruit',
                   value_name='Weight')

     State   Fruit  Weight
0    Texas   Apple      12
1  Arizona   Apple       9
2  Florida   Apple       0
3    Texas  Orange      10
4  Arizona  Orange       7
5  Florida  Orange      14
6    Texas  Banana      40
7  Arizona  Banana      12
8  Florida  Banana     190

### How it works...

### There's more...

In [16]:
state_fruit2.melt()

   variable    value
0     State    Texas
1     State  Arizona
2     State  Florida
3     Apple       12
4     Apple        9
..      ...      ...
7    Orange        7
8    Orange       14
9    Banana       40
10   Banana       12
11   Banana      190

[12 rows x 2 columns]

In [17]:
state_fruit2.melt(id_vars='State')

     State variable  value
0    Texas    Apple     12
1  Arizona    Apple      9
2  Florida    Apple      0
3    Texas   Orange     10
4  Arizona   Orange      7
5  Florida   Orange     14
6    Texas   Banana     40
7  Arizona   Banana     12
8  Florida   Banana    190

## Stacking multiple groups of variables simultaneously

In [18]:
movie = pd.read_csv('../data/movie.csv')
actor = movie[['movie_title', 'actor_1_name',
               'actor_2_name', 'actor_3_name',
               'actor_1_facebook_likes',
               'actor_2_facebook_likes',
               'actor_3_facebook_likes']]
actor.head()

,movie_title,actor_1_name,actor_2_name,actor_3_name,actor_1_facebook_likes,actor_2_facebook_likes,actor_3_facebook_likes
0,Avatar,CCH Pounder,Joel David Moore,Wes Studi,1000.0,936.0,855.0
1,Pirates of the Caribbean: At World's...,Johnny Depp,Orlando Bloom,Jack Davenport,40000.0,5000.0,1000.0
2,Spectre,Christoph Waltz,Rory Kinnear,Stephanie Sigman,11000.0,393.0,161.0
3,The Dark Knight Rises,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,27000.0,23000.0,23000.0
4,Star Wars: Episode VII - The Force A...,Doug Walker,Rob Walker,NaN,131.0,12.0,NaN

### How to do it...

In [19]:
def change_col_name(col_name):
    col_name = col_name.replace('_name', '')
    if 'facebook' in col_name:
        fb_idx = col_name.find('facebook')
        col_name = (col_name[:5] + col_name[fb_idx - 1:]
               + col_name[5:fb_idx-1])
    return col_name

In [20]:
actor2 = actor.rename(columns=change_col_name)
actor2

,movie_title,actor_1,actor_2,actor_3,actor_facebook_likes_1,actor_facebook_likes_2,actor_facebook_likes_3
0,Avatar,CCH Pounder,Joel David Moore,Wes Studi,1000.0,936.0,855.0
1,Pirates of the Caribbean: At World's...,Johnny Depp,Orlando Bloom,Jack Davenport,40000.0,5000.0,1000.0
2,Spectre,Christoph Waltz,Rory Kinnear,Stephanie Sigman,11000.0,393.0,161.0
3,The Dark Knight Rises,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,27000.0,23000.0,23000.0
4,Star Wars: Episode VII - The Force A...,Doug Walker,Rob Walker,NaN,131.0,12.0,NaN
...,...,...,...,...,...,...,...
4911,Signed Sealed Delivered,Eric Mabius,Daphne Zuniga,Crystal Lowe,637.0,470.0,318.0
4912,The Following,Natalie Zea,Valorie Curry,Sam Underwood,841.0,593.0,319.0
4913,A Plague So Pleasant,Eva Boehnke,Maxwell Moody,David Chandler,0.0,0.0,0.0
4914,Shanghai Calling,Alan Ruck,Daniel Henney,Eliza Coupe,946.0,719.0,489.0
4915,My Date with Drew,John August,Brian Herzlinger,Jon Gunn,86.0,23.0,16.0

In [21]:
stubs = ['actor', 'actor_facebook_likes']
actor2_tidy = pd.wide_to_long(actor2,
    stubnames=stubs,
    i=['movie_title'],
    j='actor_num',
    sep='_')
actor2_tidy.head()

,,actor,actor_facebook_likes
movie_title,actor_num,,
Avatar,1,CCH Pounder,1000.0
Pirates of the Caribbean: At World's End,1,Johnny Depp,40000.0
Spectre,1,Christoph Waltz,11000.0
The Dark Knight Rises,1,Tom Hardy,27000.0
Star Wars: Episode VII - The Force Awakens,1,Doug Walker,131.0

### How it works...

### There's more...

In [22]:
df = pd.read_csv('../data/stackme.csv')
df

  State Country    a1   b2   Test  d  e
0    TX      US  0.45  0.3  Test1  2  6
1    MA      US  0.03  1.2  Test2  9  7
2    ON     CAN  0.70  4.2  Test3  4  2

In [23]:
df.rename(columns = {'a1':'group1_a1', 'b2':'group1_b2',
                     'd':'group2_a1', 'e':'group2_b2'})

  State Country  group1_a1  group1_b2   Test  group2_a1  group2_b2
0    TX      US       0.45        0.3  Test1          2          6
1    MA      US       0.03        1.2  Test2          9          7
2    ON     CAN       0.70        4.2  Test3          4          2

In [24]:
pd.wide_to_long(
       df.rename(columns = {'a1':'group1_a1',
                 'b2':'group1_b2',
                 'd':'group2_a1', 'e':'group2_b2'}),
    stubnames=['group1', 'group2'],
    i=['State', 'Country', 'Test'],
    j='Label',
    suffix='.+',
    sep='_')

                           group1  group2
State Country Test  Label
TX    US      Test1 a1       0.45       2
                    b2       0.30       6
MA    US      Test2 a1       0.03       9
                    b2       1.20       7
ON    CAN     Test3 a1       0.70       4
                    b2       4.20       2

## Inverting stacked data

### How to do it...

In [25]:
usecol_func = lambda x: 'UGDS_' in x or x == 'INSTNM'
college = pd.read_csv('../data/college.csv',
    index_col='INSTNM',
    usecols=usecol_func)
college

,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,...,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN
INSTNM,,,,,,,,,
Alabama A & M University,0.0333,0.9353,0.0055,0.0019,...,0.0019,0.0000,0.0059,0.0138
University of Alabama at Birmingham,0.5922,0.2600,0.0283,0.0518,...,0.0007,0.0368,0.0179,0.0100
Amridge University,0.2990,0.4192,0.0069,0.0034,...,0.0000,0.0000,0.0000,0.2715
University of Alabama in Huntsville,0.6988,0.1255,0.0382,0.0376,...,0.0002,0.0172,0.0332,0.0350
Alabama State University,0.0158,0.9208,0.0121,0.0019,...,0.0006,0.0098,0.0243,0.0137
...,...,...,...,...,...,...,...,...,...
SAE Institute of Technology San Francisco,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN
Rasmussen College - Overland Park,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN
National Personal Training Institute of Cleveland,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN
Bay Area Medical Academy - San Jose Satellite Location,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN
Excel Learning Center-San Antonio South,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN

In [26]:
college_stacked = college.stack()
college_stacked

INSTNM
Alabama A & M University         UGDS_WHITE    0.0333
                                 UGDS_BLACK    0.9353
                                 UGDS_HISP     0.0055
                                 UGDS_ASIAN    0.0019
                                 UGDS_AIAN     0.0024
                                                ...
Coastal Pines Technical College  UGDS_AIAN     0.0034
                                 UGDS_NHPI     0.0017
                                 UGDS_2MOR     0.0191
                                 UGDS_NRA      0.0028
                                 UGDS_UNKN     0.0056
Length: 61866, dtype: float64

In [27]:
college_stacked.unstack()

,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,...,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN
INSTNM,,,,,,,,,
Alabama A & M University,0.0333,0.9353,0.0055,0.0019,...,0.0019,0.0000,0.0059,0.0138
University of Alabama at Birmingham,0.5922,0.2600,0.0283,0.0518,...,0.0007,0.0368,0.0179,0.0100
Amridge University,0.2990,0.4192,0.0069,0.0034,...,0.0000,0.0000,0.0000,0.2715
University of Alabama in Huntsville,0.6988,0.1255,0.0382,0.0376,...,0.0002,0.0172,0.0332,0.0350
Alabama State University,0.0158,0.9208,0.0121,0.0019,...,0.0006,0.0098,0.0243,0.0137
...,...,...,...,...,...,...,...,...,...
Hollywood Institute of Beauty Careers-West Palm Beach,0.2182,0.4182,0.2364,0.0182,...,0.0000,0.0000,0.0182,0.0909
Hollywood Institute of Beauty Careers-Casselberry,0.1200,0.3333,0.4400,0.0000,...,0.0000,0.0400,0.0000,0.0667
Coachella Valley Beauty College-Beaumont,0.3284,0.1045,0.4925,0.0149,...,0.0149,0.0149,0.0000,0.0000
Dewey University-Mayaguez,0.0000,0.0000,1.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000
Coastal Pines Technical College,0.6762,0.2508,0.0359,0.0045,...,0.0017,0.0191,0.0028,0.0056

In [28]:
college2 = pd.read_csv('../data/college.csv',
   usecols=usecol_func)
college2

,INSTNM,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,...,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN
0,Alabama A & M University,0.0333,0.9353,0.0055,...,0.0019,0.0000,0.0059,0.0138
1,University of Alabama at Birmingham,0.5922,0.2600,0.0283,...,0.0007,0.0368,0.0179,0.0100
2,Amridge University,0.2990,0.4192,0.0069,...,0.0000,0.0000,0.0000,0.2715
3,University of Alabama in Huntsville,0.6988,0.1255,0.0382,...,0.0002,0.0172,0.0332,0.0350
4,Alabama State University,0.0158,0.9208,0.0121,...,0.0006,0.0098,0.0243,0.0137
...,...,...,...,...,...,...,...,...,...
7530,SAE Institute of Technology San Fra...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN
7531,Rasmussen College - Overland Park,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN
7532,National Personal Training Institute...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN
7533,Bay Area Medical Academy - San Jose ...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN
7534,Excel Learning Center-San Antonio South,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN

In [29]:
college_melted = college2.melt(id_vars='INSTNM',
    var_name='Race',
    value_name='Percentage')
college_melted

                                        INSTNM        Race  Percentage
0                     Alabama A & M University  UGDS_WHITE      0.0333
1          University of Alabama at Birmingham  UGDS_WHITE      0.5922
2                           Amridge University  UGDS_WHITE      0.2990
3          University of Alabama in Huntsville  UGDS_WHITE      0.6988
4                     Alabama State University  UGDS_WHITE      0.0158
...                                        ...         ...         ...
67810  SAE Institute of Technology  San Fra...   UGDS_UNKN         NaN
67811        Rasmussen College - Overland Park   UGDS_UNKN         NaN
67812  National Personal Training Institute...   UGDS_UNKN         NaN
67813  Bay Area Medical Academy - San Jose ...   UGDS_UNKN         NaN
67814  Excel Learning Center-San Antonio South   UGDS_UNKN         NaN

[67815 rows x 3 columns]

In [30]:
melted_inv = college_melted.pivot(
    index='INSTNM',
    columns='Race',
    values='Percentage')
melted_inv

Race,UGDS_2MOR,UGDS_AIAN,UGDS_ASIAN,UGDS_BLACK,...,UGDS_NHPI,UGDS_NRA,UGDS_UNKN,UGDS_WHITE
INSTNM,,,,,,,,,
A & W Healthcare Educators,0.0000,0.0000,0.0000,0.9750,...,0.0000,0.0000,0.0000,0.0000
A T Still University of Health Sciences,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN
ABC Beauty Academy,0.0000,0.0000,0.9333,0.0333,...,0.0000,0.0000,0.0000,0.0000
ABC Beauty College Inc,0.0000,0.0000,0.0000,0.6579,...,0.0000,0.0000,0.0000,0.2895
AI Miami International University of Art and Design,0.0018,0.0000,0.0018,0.0198,...,0.0000,0.0025,0.4644,0.0324
...,...,...,...,...,...,...,...,...,...
Yukon Beauty College Inc,0.0000,0.1200,0.0000,0.0400,...,0.0400,0.0000,0.0000,0.8000
Z Hair Academy,0.0211,0.0000,0.0000,0.0000,...,0.0105,0.0000,0.0105,0.9368
Zane State College,0.0218,0.0029,0.0029,0.0296,...,0.0005,0.0000,0.2399,0.6995
duCret School of Arts,0.0976,0.0000,0.0732,0.1951,...,0.0000,0.0000,0.0244,0.4634
eClips School of Cosmetology and Barbering,0.0000,0.0000,0.0000,0.8554,...,0.0000,0.0000,0.0000,0.1446

In [31]:
college2_replication = (
    melted_inv.loc[college2['INSTNM'], college2.columns[1:]]
            .reset_index()
)
college2.equals(college2_replication)

True

### How it works...

### There's more...

In [32]:
college.stack().unstack(0)

INSTNM,Alabama A & M University,University of Alabama at Birmingham,Amridge University,University of Alabama in Huntsville,...,Hollywood Institute of Beauty Careers-Casselberry,Coachella Valley Beauty College-Beaumont,Dewey University-Mayaguez,Coastal Pines Technical College
UGDS_WHITE,0.0333,0.5922,0.2990,0.6988,...,0.1200,0.3284,0.0,0.6762
UGDS_BLACK,0.9353,0.2600,0.4192,0.1255,...,0.3333,0.1045,0.0,0.2508
UGDS_HISP,0.0055,0.0283,0.0069,0.0382,...,0.4400,0.4925,1.0,0.0359
UGDS_ASIAN,0.0019,0.0518,0.0034,0.0376,...,0.0000,0.0149,0.0,0.0045
UGDS_AIAN,0.0024,0.0022,0.0000,0.0143,...,0.0000,0.0299,0.0,0.0034
UGDS_NHPI,0.0019,0.0007,0.0000,0.0002,...,0.0000,0.0149,0.0,0.0017
UGDS_2MOR,0.0000,0.0368,0.0000,0.0172,...,0.0400,0.0149,0.0,0.0191
UGDS_NRA,0.0059,0.0179,0.0000,0.0332,...,0.0000,0.0000,0.0,0.0028
UGDS_UNKN,0.0138,0.0100,0.2715,0.0350,...,0.0667,0.0000,0.0,0.0056

In [33]:
college.T
college.transpose()

INSTNM,Alabama A & M University,University of Alabama at Birmingham,Amridge University,University of Alabama in Huntsville,...,Rasmussen College - Overland Park,National Personal Training Institute of Cleveland,Bay Area Medical Academy - San Jose Satellite Location,Excel Learning Center-San Antonio South
UGDS_WHITE,0.0333,0.5922,0.2990,0.6988,...,NaN,NaN,NaN,NaN
UGDS_BLACK,0.9353,0.2600,0.4192,0.1255,...,NaN,NaN,NaN,NaN
UGDS_HISP,0.0055,0.0283,0.0069,0.0382,...,NaN,NaN,NaN,NaN
UGDS_ASIAN,0.0019,0.0518,0.0034,0.0376,...,NaN,NaN,NaN,NaN
UGDS_AIAN,0.0024,0.0022,0.0000,0.0143,...,NaN,NaN,NaN,NaN
UGDS_NHPI,0.0019,0.0007,0.0000,0.0002,...,NaN,NaN,NaN,NaN
UGDS_2MOR,0.0000,0.0368,0.0000,0.0172,...,NaN,NaN,NaN,NaN
UGDS_NRA,0.0059,0.0179,0.0000,0.0332,...,NaN,NaN,NaN,NaN
UGDS_UNKN,0.0138,0.0100,0.2715,0.0350,...,NaN,NaN,NaN,NaN

## Unstacking after a groupby aggregation

### How to do it...

In [34]:
employee = pd.read_csv('../data/employee.csv')
(employee
    .groupby('RACE')
    ['BASE_SALARY']
    .mean()
    .astype(int)
)

RACE
American Indian or Alaskan Native    60272
Asian/Pacific Islander               61660
Black or African American            50137
Hispanic/Latino                      52345
Others                               51278
White                                64419
Name: BASE_SALARY, dtype: int64

In [35]:
(employee
    .groupby(['RACE', 'GENDER'])
    ['BASE_SALARY']
    .mean()
    .astype(int)
)

RACE                               GENDER
American Indian or Alaskan Native  Female    60238
                                   Male      60305
Asian/Pacific Islander             Female    63226
                                   Male      61033
Black or African American          Female    48915
                                             ...
Hispanic/Latino                    Male      54782
Others                             Female    63785
                                   Male      38771
White                              Female    66793
                                   Male      63940
Name: BASE_SALARY, Length: 12, dtype: int64

In [36]:
(employee
    .groupby(['RACE', 'GENDER'])
    ['BASE_SALARY']
    .mean()
    .astype(int)
    .unstack('GENDER')
)

GENDER                             Female   Male
RACE
American Indian or Alaskan Native   60238  60305
Asian/Pacific Islander              63226  61033
Black or African American           48915  51082
Hispanic/Latino                     46503  54782
Others                              63785  38771
White                               66793  63940

In [37]:
(employee
    .groupby(['RACE', 'GENDER'])
    ['BASE_SALARY']
    .mean()
    .astype(int)
    .unstack('RACE')
)

RACE,American Indian or Alaskan Native,Asian/Pacific Islander,Black or African American,Hispanic/Latino,Others,White
GENDER,,,,,,
Female,60238,63226,48915,46503,63785,66793
Male,60305,61033,51082,54782,38771,63940

### How it works...

### There's more...

In [38]:
(employee
    .groupby(['RACE', 'GENDER'])
    ['BASE_SALARY']
    .agg(['mean', 'max', 'min'])
    .astype(int)
)

                                           mean     max    min
RACE                              GENDER
American Indian or Alaskan Native Female  60238   98536  26125
                                  Male    60305   81239  26125
Asian/Pacific Islander            Female  63226  130416  26125
                                  Male    61033  163228  27914
Black or African American         Female  48915  150416  24960
...                                         ...     ...    ...
Hispanic/Latino                   Male    54782  165216  26104
Others                            Female  63785   63785  63785
                                  Male    38771   38771  38771
White                             Female  66793  178331  27955
                                  Male    63940  210588  26125

[12 rows x 3 columns]

In [39]:
(employee
    .groupby(['RACE', 'GENDER'])
    ['BASE_SALARY']
    .agg(['mean', 'max', 'min'])
    .astype(int)
    .unstack('GENDER')
)

                                    mean            max            min
GENDER                            Female   Male  Female    Male Female   Male
RACE
American Indian or Alaskan Native  60238  60305   98536   81239  26125  26125
Asian/Pacific Islander             63226  61033  130416  163228  26125  27914
Black or African American          48915  51082  150416  275000  24960  26125
Hispanic/Latino                    46503  54782  126115  165216  26125  26104
Others                             63785  38771   63785   38771  63785  38771
White                              66793  63940  178331  210588  27955  26125

## Replicating pivot_table with a groupby aggregation

### How to do it...

In [40]:
flights = pd.read_csv('../data/flights.csv')
fpt = flights.pivot_table(
    index='AIRLINE',
    columns='ORG_AIR',
    values='CANCELLED',
    aggfunc='sum',
    fill_value=0).round(2)
fpt

ORG_AIR  ATL  DEN  DFW  IAH  ...  MSP  ORD  PHX  SFO
AIRLINE                      ...
AA         3    4   86    3  ...    3   35    4    2
AS         0    0    0    0  ...    0    0    0    0
B6         0    0    0    0  ...    0    0    0    1
DL        28    1    0    0  ...    4    0    1    2
EV        18    6   27   36  ...    6   53    0    0
...      ...  ...  ...  ...  ...  ...  ...  ...  ...
OO         3   25    2   10  ...    4   41    9   33
UA         2    9    1   23  ...    2   25    3   19
US         0    0    2    2  ...    0    6    7    3
VX         0    0    0    0  ...    0    0    0    3
WN         9   13    0    0  ...    1    0    6   25

[14 rows x 10 columns]

In [41]:
(flights
    .groupby(['AIRLINE', 'ORG_AIR'])
    ['CANCELLED']
    .sum()
)

AIRLINE  ORG_AIR
AA       ATL         3
         DEN         4
         DFW        86
         IAH         3
         LAS         3
                    ..
WN       LAS         7
         LAX        32
         MSP         1
         PHX         6
         SFO        25
Name: CANCELLED, Length: 114, dtype: int64

In [42]:
fpg = (flights
    .groupby(['AIRLINE', 'ORG_AIR'])
    ['CANCELLED']
    .sum()
    .unstack('ORG_AIR', fill_value=0)
)

In [43]:
fpt.equals(fpg)

True

### How it works...

### There's more...

In [44]:
flights.pivot_table(index=['AIRLINE', 'MONTH'],
    columns=['ORG_AIR', 'CANCELLED'],
    values=['DEP_DELAY', 'DIST'],
    aggfunc=['sum', 'mean'],
    fill_value=0)

                    sum                    ...         mean         \
              DEP_DELAY                    ...         DIST
ORG_AIR             ATL          DEN       ...          PHX
CANCELLED             0    1       0    1  ...            0      1
AIRLINE MONTH                              ...
AA      1         -13.0  0.0   113.0  0.0  ...  1167.666667    0.0
        2         -39.0  0.0    71.0  0.0  ...  1311.461538  868.0
        3          -2.0  0.0    69.0  0.0  ...  1171.363636    0.0
        4           1.0  0.0   304.0  0.0  ...  1266.214286    0.0
        5          52.0  0.0   352.0  0.0  ...  1240.444444    0.0
...                 ...  ...     ...  ...  ...          ...    ...
WN      7        2604.0  0.0  1919.0  0.0  ...   799.160256  369.0
        8        1718.0  0.0  1180.0  0.0  ...   891.569767    0.0
        9        1033.0  0.0   705.0  0.0  ...   872.840000    0.0
        11        700.0  0.0  1372.0  0.0  ...   823.258741  872.0
        12       1679.0  0.0  1898.0  0.0  ...   778.420690    0.0



ORG_AIR                SFO
CANCELLED                0       1
AIRLINE MONTH
AA      1      1860.166667     0.0
        2      1337.916667  2586.0
        3      1502.758621     0.0
        4      1646.903226     0.0
        5      1436.892857     0.0
...                    ...     ...
WN      7       636.210526     0.0
        8       644.857143   392.0
        9       731.578947   354.5
        11      580.875000   392.0
        12      782.256410     0.0

[149 rows x 80 columns]

In [55]:
flights.columns.sort_values()

Index(['AIRLINE', 'AIR_TIME', 'ARR_DELAY', 'CANCELLED', 'DAY', 'DEP_DELAY',
       'DEST_AIR', 'DIST', 'DIVERTED', 'MONTH', 'ORG_AIR', 'SCHED_ARR',
       'SCHED_DEP', 'WEEKDAY'],
      dtype='object')

In [60]:
(flights
    .groupby(['AIRLINE', 'MONTH', 'ORG_AIR', 'CANCELLED'])
    [['DEP_DELAY', 'DIST']]
    .agg(['mean', 'sum'])
    .unstack(['ORG_AIR', 'CANCELLED'], fill_value=0)
    .swaplevel(0, 1, axis='columns')
)

                    mean                       ...     sum
               DEP_DELAY                       ...    DIST
ORG_AIR              ATL             DEN       ...     PHX         SFO
CANCELLED              0    1          0    1  ...       0    1      0     1
AIRLINE MONTH                                  ...
AA      1      -3.250000  0.0   7.062500  0.0  ...   21018    0  33483     0
        2      -3.000000  NaN   5.461538  NaN  ...   17049  868  32110  2586
        3      -0.166667  NaN   7.666667  0.0  ...   25770    0  43580     0
        4       0.071429  0.0  20.266667  0.0  ...   17727    0  51054     0
        5       5.777778  0.0  23.466667  NaN  ...   11164    0  40233     0
...                  ...  ...        ...  ...  ...     ...  ...    ...   ...
WN      7      21.700000  0.0  13.143836  0.0  ...  124669  369  24176     0
        8      16.207547  0.0   7.375000  0.0  ...  153350    0  18056   784
        9       8.680672  0.0   4.378882  0.0  ...  130926    0  27800   709
        11      5.932203  NaN   8.215569  NaN  ...  117726  872  23235   784
        12     15.691589  0.0  12.166667  NaN  ...  112871    0  30508     0

[149 rows x 80 columns]

## Renaming axis levels for easy reshaping

### How to do it...

In [62]:
college = pd.read_csv('../data/college.csv')
(college
    .groupby(['STABBR', 'RELAFFIL'])
    [['UGDS', 'SATMTMID']]
    .agg(['size', 'min', 'max'])
)

                UGDS                 SATMTMID
                size    min      max     size    min    max
STABBR RELAFFIL
AK     0           7  109.0  12865.0        7    NaN    NaN
       1           3   27.0    275.0        3  503.0  503.0
AL     0          72   12.0  29851.0       72  420.0  590.0
       1          24   13.0   3033.0       24  400.0  560.0
AR     0          68   18.0  21405.0       68  427.0  565.0
...              ...    ...      ...      ...    ...    ...
WI     0          87   20.0  29302.0       87  480.0  680.0
       1          25    4.0   8212.0       25  452.0  605.0
WV     0          65   20.0  44924.0       65  430.0  530.0
       1           8   63.0   1375.0        8  455.0  510.0
WY     0          11   52.0   9910.0       11  540.0  540.0

[112 rows x 6 columns]

In [63]:
(college
    .groupby(['STABBR', 'RELAFFIL'])
    [['UGDS', 'SATMTMID']]
    .agg(['size', 'min', 'max'])
    .rename_axis(['AGG_COLS', 'AGG_FUNCS'], axis='columns')
)

AGG_COLS        UGDS                 SATMTMID
AGG_FUNCS       size    min      max     size    min    max
STABBR RELAFFIL
AK     0           7  109.0  12865.0        7    NaN    NaN
       1           3   27.0    275.0        3  503.0  503.0
AL     0          72   12.0  29851.0       72  420.0  590.0
       1          24   13.0   3033.0       24  400.0  560.0
AR     0          68   18.0  21405.0       68  427.0  565.0
...              ...    ...      ...      ...    ...    ...
WI     0          87   20.0  29302.0       87  480.0  680.0
       1          25    4.0   8212.0       25  452.0  605.0
WV     0          65   20.0  44924.0       65  430.0  530.0
       1           8   63.0   1375.0        8  455.0  510.0
WY     0          11   52.0   9910.0       11  540.0  540.0

[112 rows x 6 columns]

In [64]:
(college
    .groupby(['STABBR', 'RELAFFIL'])
    [['UGDS', 'SATMTMID']]
    .agg(['size', 'min', 'max'])
    .rename_axis(['AGG_COLS', 'AGG_FUNCS'], axis='columns')
    .stack('AGG_FUNCS')
)

/tmp/ipykernel_30607/3368669885.py:6: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  .stack('AGG_FUNCS')

AGG_COLS                      UGDS  SATMTMID
STABBR RELAFFIL AGG_FUNCS
AK     0        size           7.0       7.0
                min          109.0       NaN
                max        12865.0       NaN
       1        size           3.0       3.0
                min           27.0     503.0
...                            ...       ...
WV     1        min           63.0     455.0
                max         1375.0     510.0
WY     0        size          11.0      11.0
                min           52.0     540.0
                max         9910.0     540.0

[332 rows x 2 columns]

In [65]:
(college
    .groupby(['STABBR', 'RELAFFIL'])
    [['UGDS', 'SATMTMID']]
    .agg(['size', 'min', 'max'])
    .rename_axis(['AGG_COLS', 'AGG_FUNCS'], axis='columns')
    .stack('AGG_FUNCS')
    .swaplevel('AGG_FUNCS', 'STABBR',
       axis='index')
)

/tmp/ipykernel_30607/1992729582.py:6: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  .stack('AGG_FUNCS')

AGG_COLS                      UGDS  SATMTMID
AGG_FUNCS RELAFFIL STABBR
size      0        AK          7.0       7.0
min       0        AK        109.0       NaN
max       0        AK      12865.0       NaN
size      1        AK          3.0       3.0
min       1        AK         27.0     503.0
...                            ...       ...
                   WV         63.0     455.0
max       1        WV       1375.0     510.0
size      0        WY         11.0      11.0
min       0        WY         52.0     540.0
max       0        WY       9910.0     540.0

[332 rows x 2 columns]

In [66]:
(college
    .groupby(['STABBR', 'RELAFFIL'])
    [['UGDS', 'SATMTMID']]
    .agg(['size', 'min', 'max'])
    .rename_axis(['AGG_COLS', 'AGG_FUNCS'], axis='columns')
    .stack('AGG_FUNCS')
    .swaplevel('AGG_FUNCS', 'STABBR', axis='index')
    .sort_index(level='RELAFFIL', axis='index')
    .sort_index(level='AGG_COLS', axis='columns')
)

/tmp/ipykernel_30607/2929635990.py:6: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  .stack('AGG_FUNCS')

AGG_COLS                   SATMTMID      UGDS
AGG_FUNCS RELAFFIL STABBR
max       0        AK           NaN   12865.0
                   AL         590.0   29851.0
                   AR         565.0   21405.0
                   AS           NaN    1276.0
                   AZ         580.0  151558.0
...                             ...       ...
size      1        VI           1.0       1.0
                   VT           5.0       5.0
                   WA          17.0      17.0
                   WI          25.0      25.0
                   WV           8.0       8.0

[332 rows x 2 columns]

In [67]:
(college
    .groupby(['STABBR', 'RELAFFIL'])
    [['UGDS', 'SATMTMID']]
    .agg(['size', 'min', 'max'])
    .rename_axis(['AGG_COLS', 'AGG_FUNCS'], axis='columns')
    .stack('AGG_FUNCS')
    .unstack(['RELAFFIL', 'STABBR'])
)

/tmp/ipykernel_30607/1066076731.py:6: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  .stack('AGG_FUNCS')

AGG_COLS      UGDS                          ... SATMTMID
RELAFFIL         0      1        0       1  ...        1      0      1      0
STABBR          AK     AK       AL      AL  ...       WI     WV     WV     WY
AGG_FUNCS                                   ...
size           7.0    3.0     72.0    24.0  ...     25.0   65.0    8.0   11.0
min          109.0   27.0     12.0    13.0  ...    452.0  430.0  455.0  540.0
max        12865.0  275.0  29851.0  3033.0  ...    605.0  530.0  510.0  540.0

[3 rows x 224 columns]

In [68]:
(college
    .groupby(['STABBR', 'RELAFFIL'])
    [['UGDS', 'SATMTMID']]
    .agg(['size', 'min', 'max'])
    .rename_axis(['AGG_COLS', 'AGG_FUNCS'], axis='columns')
    .stack(['AGG_FUNCS', 'AGG_COLS'])
)

/tmp/ipykernel_30607/2021049412.py:6: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  .stack(['AGG_FUNCS', 'AGG_COLS'])

STABBR  RELAFFIL  AGG_FUNCS  AGG_COLS
AK      0         size       UGDS            7.0
                             SATMTMID        7.0
                  min        UGDS          109.0
                  max        UGDS        12865.0
        1         size       UGDS            3.0
                                          ...
WY      0         size       SATMTMID       11.0
                  min        UGDS           52.0
                             SATMTMID      540.0
                  max        UGDS         9910.0
                             SATMTMID      540.0
Length: 640, dtype: float64

In [69]:
(college
    .groupby(['STABBR', 'RELAFFIL'])
    [['UGDS', 'SATMTMID']]
    .agg(['size', 'min', 'max'])
    .rename_axis(['AGG_COLS', 'AGG_FUNCS'], axis='columns')
    .unstack(['STABBR', 'RELAFFIL'])
)

AGG_COLS  AGG_FUNCS  STABBR  RELAFFIL
UGDS      size       AK      0             7.0
                             1             3.0
                     AL      0            72.0
                             1            24.0
                     AR      0            68.0
                                         ...
SATMTMID  max        WI      1           605.0
                     WV      0           530.0
                             1           510.0
                     WY      0           540.0
                             1             NaN
Length: 708, dtype: float64

### How it works...

### There's more...

In [ ]:
(college
    .groupby(['STABBR', 'RELAFFIL'])
    ['UGDS', 'SATMTMID']
    .agg(['size', 'min', 'max'])
    .rename_axis([None, None], axis='index')
    .rename_axis([None, None], axis='columns')
)

## Tidying when multiple variables are stored as column names

### How to do it...

In [ ]:
weightlifting = pd.read_csv('../data/weightlifting_men.csv')
weightlifting

In [ ]:
(weightlifting
    .melt(id_vars='Weight Category',
          var_name='sex_age',
          value_name='Qual Total')
)

In [ ]:
(weightlifting
    .melt(id_vars='Weight Category',
          var_name='sex_age',
          value_name='Qual Total')
    ['sex_age']
    .str.split(expand=True)
)

In [ ]:
(weightlifting
    .melt(id_vars='Weight Category',
          var_name='sex_age',
          value_name='Qual Total')
    ['sex_age']
    .str.split(expand=True)
    .rename(columns={0:'Sex', 1:'Age Group'})
)

In [ ]:
(weightlifting
    .melt(id_vars='Weight Category',
          var_name='sex_age',
          value_name='Qual Total')
    ['sex_age']
    .str.split(expand=True)
    .rename(columns={0:'Sex', 1:'Age Group'})
    .assign(Sex=lambda df_: df_.Sex.str[0])
)

In [ ]:
melted = (weightlifting
    .melt(id_vars='Weight Category',
          var_name='sex_age',
          value_name='Qual Total')
)
tidy = pd.concat([melted
           ['sex_age']
           .str.split(expand=True)
           .rename(columns={0:'Sex', 1:'Age Group'})
           .assign(Sex=lambda df_: df_.Sex.str[0]),
          melted[['Weight Category', 'Qual Total']]],
          axis='columns'
)
tidy

In [ ]:
melted = (weightlifting
    .melt(id_vars='Weight Category',
          var_name='sex_age',
          value_name='Qual Total')
)
(melted
    ['sex_age']
    .str.split(expand=True)
    .rename(columns={0:'Sex', 1:'Age Group'})
    .assign(Sex=lambda df_: df_.Sex.str[0],
            Category=melted['Weight Category'],
            Total=melted['Qual Total'])
)

### How it works...

### There's more...

In [ ]:
tidy2 = (weightlifting
    .melt(id_vars='Weight Category',
          var_name='sex_age',
          value_name='Qual Total')
    .assign(Sex=lambda df_:df_.sex_age.str[0],
            **{'Age Group':(lambda df_: (df_
                .sex_age
                .str.extract(r'(\d{2}[-+](?:\d{2})?)',
                             expand=False)))})
    .drop(columns='sex_age')
)

In [ ]:
tidy2

In [ ]:
tidy.sort_index(axis=1).equals(tidy2.sort_index(axis=1))

## Tidying when multiple variables are stored is a single column

### How to do it...

In [ ]:
inspections = pd.read_csv('../data/restaurant_inspections.csv',
    parse_dates=['Date'])
inspections

In [ ]:
inspections.pivot(index=['Name', 'Date'],
    columns='Info', values='Value')

In [ ]:
inspections.set_index(['Name','Date', 'Info'])

In [ ]:
(inspections
    .set_index(['Name','Date', 'Info'])
    .unstack('Info')
)

In [ ]:
(inspections
    .set_index(['Name','Date', 'Info'])
    .unstack('Info')
    .reset_index(col_level=-1)
)

In [ ]:
def flatten0(df_):
    df_.columns = df_.columns.droplevel(0).rename(None)
    return df_

In [ ]:
(inspections
    .set_index(['Name','Date', 'Info'])
    .unstack('Info')
    .reset_index(col_level=-1)
    .pipe(flatten0)
)

In [ ]:
(inspections
    .set_index(['Name','Date', 'Info'])
    .squeeze()
    .unstack('Info')
    .reset_index()
    .rename_axis(None, axis='columns')
)

### How it works...

### There's more...

In [ ]:
(inspections
    .pivot_table(index=['Name', 'Date'],
                 columns='Info',
                 values='Value',
                 aggfunc='first')
    .reset_index()
    .rename_axis(None, axis='columns')
)

## Tidying when two or more values are stored in the same cell

### How to do it..

In [ ]:
cities = pd.read_csv('../data/texas_cities.csv')
cities

In [ ]:
geolocations = cities.Geolocation.str.split(pat='. ',
    expand=True)
geolocations.columns = ['latitude', 'latitude direction',
    'longitude', 'longitude direction']

In [ ]:
geolocations = geolocations.astype({'latitude':'float',
   'longitude':'float'})
geolocations.dtypes

In [ ]:
(geolocations
    .assign(city=cities['City'])
)

### How it works...

In [ ]:
geolocations.apply(pd.to_numeric, errors='ignore')

### There's more...

In [ ]:
cities.Geolocation.str.split(pat=r'° |, ', expand=True)

In [ ]:
cities.Geolocation.str.extract(r'([0-9.]+). (N|S), ([0-9.]+). (E|W)',
   expand=True)

## Tidying when variables are stored in column names and values

### Getting ready

In [ ]:
sensors = pd.read_csv('../data/sensors.csv')
sensors

In [ ]:
sensors.melt(id_vars=['Group', 'Property'], var_name='Year')

In [ ]:
(sensors
    .melt(id_vars=['Group', 'Property'], var_name='Year')
    .pivot_table(index=['Group', 'Year'],
                 columns='Property', values='value')
    .reset_index()
    .rename_axis(None, axis='columns')
)

### How it works...

### There's more...

In [ ]:
(sensors
    .set_index(['Group', 'Property'])
    .stack()
    .unstack('Property')
    .rename_axis(['Group', 'Year'], axis='index')
    .rename_axis(None, axis='columns')
    .reset_index()
)